services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3307:3306
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
